# Generated by Django 2.1.1 on 2018-09-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='生日',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
